import React, { useState, useEffect, useLayoutEffect } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/layout'
import { isAuthenticated } from '../store/reducers/user.reducer'
import HomeComponent from '../components/homeComponent'

export default function Home() {
  const user = useSelector(state => state.userReducer)
  const dispatch = useDispatch()

  useEffect(() => {
    if (!user.authenticated) {
      dispatch(isAuthenticated())
    }
  }, [user.authenticated])

  return <>
    <Head>
      <title>Facebook</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    {!user.authenticated ? <div>
      <Image alt="Facebook Logo" src="/images/facebook_logo.svg" width="300" height="100" />
      <div style={{ marginLeft: '30px' }}>
        <h2>
          Facebook helps you connect and share with the people in your life.
        </h2>
        <p>
          <Link href='/signin'>Sign in</Link> or <Link href="/signup">Sign up</Link>
        </p>
      </div>
    </div> : <Layout><HomeComponent /> </Layout>}
  </>
}