import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/facebook.ico" />
      </Head>
      <div>
        <Image alt="Facebook Logo" src="/images/facebook_logo.svg" width="300" height="100" />
        <div style={{ marginLeft: '30px' }}>
          <h2>
            Facebook helps you connect and share with the people in your life.
          </h2>
          <p>
            <Link href='/signin'>Sign in</Link> or <Link href="/signup">Sign up</Link>
          </p>
        </div>
      </div>
    </div>
  )
}
