import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/facebook.ico" />
      </Head>
      <div className={styles['home-page']}>
        <Image alt="Facebook Logo" src="/facebook_logo.svg" width="300" height="100" />
        <div style={{ marginLeft: '30px' }}>
          <h2 className={styles.title}>
            Facebook helps you connect and share with the people in your life.
          </h2>
          <p>
            <Link href='/signin'>Sign in</Link> or <Link href="/signup">Sign up</Link>
          </p>
        </div>
      </div>
    </div>
  )
}
